theme: jekyll-theme-modernist
title: Multi Controller V1.0
description: They contain an LCD display that is 20 characters wide and 2 lines high surrounded by 2 buttons labeled Fan+, Fan- controlls with LED indicator and Buzzer, and controlls RGB Leds Strip.
show_downloads: false
